// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using My_Barbershop.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace My_Barbershop.Migrations
{
    [DbContext(typeof(BarbershopContext))]
    [Migration("20250610193617_AddColumnCreatedAt")]
    partial class AddColumnCreatedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("My_Barbershop.Models.Administrator", b =>
                {
                    b.Property<long>("AdminPassport")
                        .HasColumnType("bigint")
                        .HasColumnName("admin_passport");

                    b.Property<string>("AdmFio")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("adm_fio");

                    b.Property<long?>("AdminPhnumber")
                        .HasColumnType("bigint")
                        .HasColumnName("admin_phnumber");

                    b.Property<long?>("BNum")
                        .HasColumnType("bigint")
                        .HasColumnName("b_num");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.HasKey("AdminPassport")
                        .HasName("administrator_pkey");

                    b.HasIndex("BNum");

                    b.ToTable("administrator", (string)null);
                });

            modelBuilder.Entity("My_Barbershop.Models.Appointment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("Appointmentdate")
                        .HasColumnType("date")
                        .HasColumnName("appointmentdate");

                    b.Property<TimeOnly>("Appointmenttime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("appointmenttime");

                    b.Property<long?>("Barberpassport")
                        .HasColumnType("bigint")
                        .HasColumnName("barberpassport");

                    b.Property<long?>("Clientphone")
                        .HasColumnType("bigint")
                        .HasColumnName("clientphone");

                    b.Property<string>("Servicename")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("servicename");

                    b.HasKey("Id")
                        .HasName("appointment_pkey");

                    b.HasIndex("Barberpassport");

                    b.HasIndex("Clientphone");

                    b.HasIndex("Servicename");

                    b.ToTable("appointment", (string)null);
                });

            modelBuilder.Entity("My_Barbershop.Models.Barber", b =>
                {
                    b.Property<long>("BarberPassport")
                        .HasColumnType("bigint")
                        .HasColumnName("barber_passport");

                    b.Property<long?>("BNum")
                        .HasColumnType("bigint")
                        .HasColumnName("b_num");

                    b.Property<string>("BarberFio")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("barber_fio");

                    b.Property<long?>("BarberPhnumber")
                        .HasColumnType("bigint")
                        .HasColumnName("barber_phnumber");

                    b.HasKey("BarberPassport")
                        .HasName("barber_pkey");

                    b.HasIndex("BNum");

                    b.ToTable("barber", (string)null);
                });

            modelBuilder.Entity("My_Barbershop.Models.Barberclient", b =>
                {
                    b.Property<long?>("Barbpass")
                        .HasColumnType("bigint")
                        .HasColumnName("barbpass");

                    b.Property<long?>("Clientphone")
                        .HasColumnType("bigint")
                        .HasColumnName("clientphone");

                    b.HasIndex("Barbpass");

                    b.HasIndex("Clientphone");

                    b.ToTable("barberclient", (string)null);
                });

            modelBuilder.Entity("My_Barbershop.Models.Barberservice", b =>
                {
                    b.Property<long?>("Barbpass")
                        .HasColumnType("bigint")
                        .HasColumnName("barbpass");

                    b.Property<string>("Servname")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("servname");

                    b.HasIndex("Barbpass");

                    b.HasIndex("Servname");

                    b.ToTable("barberservice", (string)null);
                });

            modelBuilder.Entity("My_Barbershop.Models.Barbershop", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("barbershop_pkey");

                    b.ToTable("barbershop", (string)null);
                });

            modelBuilder.Entity("My_Barbershop.Models.Client", b =>
                {
                    b.Property<long>("ClientPhnum")
                        .HasColumnType("bigint")
                        .HasColumnName("client_phnum");

                    b.Property<int?>("BonusPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bonus_points")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime?>("CardIssueDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("card_issue_date");

                    b.Property<string>("ClFio")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("cl_fio");

                    b.Property<string>("DiscountCard")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("discount_card");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.HasKey("ClientPhnum")
                        .HasName("client_pkey");

                    b.ToTable("client", (string)null);
                });

            modelBuilder.Entity("My_Barbershop.Models.Service", b =>
                {
                    b.Property<string>("ServName")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("serv_name");

                    b.Property<double?>("Durofwork")
                        .HasColumnType("double precision")
                        .HasColumnName("durofwork");

                    b.Property<double?>("ServPrice")
                        .HasColumnType("double precision")
                        .HasColumnName("serv_price");

                    b.HasKey("ServName")
                        .HasName("service_pkey");

                    b.ToTable("service", (string)null);
                });

            modelBuilder.Entity("My_Barbershop.Models.Administrator", b =>
                {
                    b.HasOne("My_Barbershop.Models.Barbershop", "BNumNavigation")
                        .WithMany("Administrators")
                        .HasForeignKey("BNum")
                        .HasConstraintName("administrator_b_num_fkey");

                    b.Navigation("BNumNavigation");
                });

            modelBuilder.Entity("My_Barbershop.Models.Appointment", b =>
                {
                    b.HasOne("My_Barbershop.Models.Barber", "BarberpassportNavigation")
                        .WithMany("Appointments")
                        .HasForeignKey("Barberpassport")
                        .HasConstraintName("appointment_barberpassport_fkey");

                    b.HasOne("My_Barbershop.Models.Client", "ClientphoneNavigation")
                        .WithMany("Appointments")
                        .HasForeignKey("Clientphone")
                        .HasConstraintName("appointment_clientphone_fkey");

                    b.HasOne("My_Barbershop.Models.Service", "ServicenameNavigation")
                        .WithMany("Appointments")
                        .HasForeignKey("Servicename")
                        .HasConstraintName("appointment_servicename_fkey");

                    b.Navigation("BarberpassportNavigation");

                    b.Navigation("ClientphoneNavigation");

                    b.Navigation("ServicenameNavigation");
                });

            modelBuilder.Entity("My_Barbershop.Models.Barber", b =>
                {
                    b.HasOne("My_Barbershop.Models.Barbershop", "BNumNavigation")
                        .WithMany("Barbers")
                        .HasForeignKey("BNum")
                        .HasConstraintName("barber_b_num_fkey");

                    b.Navigation("BNumNavigation");
                });

            modelBuilder.Entity("My_Barbershop.Models.Barberclient", b =>
                {
                    b.HasOne("My_Barbershop.Models.Barber", "BarbpassNavigation")
                        .WithMany()
                        .HasForeignKey("Barbpass")
                        .HasConstraintName("barberclient_barbpass_fkey");

                    b.HasOne("My_Barbershop.Models.Client", "ClientphoneNavigation")
                        .WithMany()
                        .HasForeignKey("Clientphone")
                        .HasConstraintName("barberclient_clientphone_fkey");

                    b.Navigation("BarbpassNavigation");

                    b.Navigation("ClientphoneNavigation");
                });

            modelBuilder.Entity("My_Barbershop.Models.Barberservice", b =>
                {
                    b.HasOne("My_Barbershop.Models.Barber", "BarbpassNavigation")
                        .WithMany()
                        .HasForeignKey("Barbpass")
                        .HasConstraintName("barberservice_barbpass_fkey");

                    b.HasOne("My_Barbershop.Models.Service", "ServnameNavigation")
                        .WithMany()
                        .HasForeignKey("Servname")
                        .HasConstraintName("barberservice_servname_fkey");

                    b.Navigation("BarbpassNavigation");

                    b.Navigation("ServnameNavigation");
                });

            modelBuilder.Entity("My_Barbershop.Models.Barber", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("My_Barbershop.Models.Barbershop", b =>
                {
                    b.Navigation("Administrators");

                    b.Navigation("Barbers");
                });

            modelBuilder.Entity("My_Barbershop.Models.Client", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("My_Barbershop.Models.Service", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
